export const recipesData = {
  recipes: [
    {
      id: 1,
      name: "Spaghetti bolognaise",
      ingredients: [
        { name: "250g spaghetti", pic: "spaghetti" },
        { name: "1 boîte tomates pelées", pic: "tomates-pelées" },
        { name: "1 boîte contentré de tomates", pic: "concentré-tomates" },
        { name: "250g haché porc-boeuf", pic: "haché" },
        { name: "1 oignon", pic: "oignon" },
        { name: "1 gousse d'ail", pic: "ail" },
        { name: "laurier", pic: "laurier" },
        { name: "huile", pic: "huile" },
      ],
      serving: 2,
      time: "1h20",
      pic: "spaghetti-bolo.jpg",
      link: "https://www.cuisineaz.com/recettes/spaghettis-bolognaise-maison-56002.aspx",
    },
    {
      id: 2,
      name: "Quiche chorizo",
      ingredients: [
        { name: "1 pâte brisée", pic: "pâte-brisée" },
        { name: "1 chorizo", pic: "chorizo" },
        { name: "tomates séchées", pic: "tomates-séchées" },
        { name: "1 poivron jaune", pic: "poivron-jaune" },
        { name: "3 oeufs", pic: "oeuf" },
        { name: "25cl crème fraîche", pic: "crème-fraîche" },
        { name: "1 bloc de feta", pic: "feta" },
      ],
      serving: 4,
      time: "1h",
      pic: "quiche-chorizo.jpg",
      link: "https://www.ptitchef.com/recettes/entree/tarte-soleil-aux-poivrons-chorizo-et-feta-fid-1565800",
    },
    {
      id: 3,
      name: "Salisbury steak",
      ingredients: [
        { name: "450g haché boeuf", pic: "haché" },
        { name: "1 oeuf", pic: "oeuf" },
        { name: "35g chapelure", pic: "chapelure" },
        { name: "ketchup", pic: "ketchup" },
        { name: "sauce Worcestershire", pic: "Worcestershire" },
        { name: "1 gousse d'ail", pic: "ail" },
        { name: "huile", pic: "huile" },
        { name: "beurre", pic: "beurre" },
        { name: "1 oignon", pic: "oignon" },
        { name: "50g champignons", pic: "champignons" },
        { name: "farine", pic: "farine" },
        { name: "concentré de tomates", pic: "concentré-tomates" },
      ],
      serving: 4,
      time: "40 min",
      pic: "salisbury-steak.jpg",
      link: "https://www.delish.com/cooking/recipe-ideas/recipes/a54937/best-salisbury-steak-recipe/",
    },
    {
      id: 4,
      name: "Pain de viande",
      ingredients: [
        { name: "1 oignon", pic: "oignon" },
        { name: "500g haché boeuf", pic: "haché" },
        { name: "2 tartines", pic: "tartine" },
        { name: "ketchup", pic: "ketchup" },
        { name: "1 oeuf", pic: "oeuf" },
      ],
      serving: 4,
      time: "45 min",
      pic: "pain-de-viande.jpeg",
      link: "https://www.marmiton.org/recettes/recette_pain-de-viande-rapide_18189.aspx",
    },
    {
      id: 5,
      name: "Pâtes merguez feta",
      ingredients: [
        { name: "1 bloc de feta", pic: "feta" },
        { name: "250g farfalle", pic: "farfalle" },
        { name: "1 poivron jaune", pic: "poivron-jaune" },
        { name: "2 tomates coeur de boeuf", pic: "tomate-boeuf" },
        { name: "4 merguez", pic: "merguez" },
        { name: "1/2 oignon", pic: "oignon" },
      ],
      serving: 2,
      time: "35 min",
      pic: "pâtes-merguez-feta.jpg",
    },
    {
      id: 6,
      name: "Buffalo hot wings",
      ingredients: [
        { name: "12 ailes de poulet", pic: "ailes-poulet" },
        { name: "125g farine", pic: "farine" },
        { name: "2 oeufs", pic: "oeuf" },
        { name: "tabasco", pic: "tabasco" },
        { name: "piment de cayenne", pic: "cayenne" },
        { name: "poudre d'ail", pic: "poudre-ail" },
      ],
      serving: 2,
      time: "24 min",
      pic: "buffalo-wing.jpg",
      link: "https://www.recette-americaine.com/plat/kfc-hot-wings-ailes-piquantes.php",
    },
    {
      id: 7,
      name: "Nigella's cripsy lamb chops",
      ingredients: [
        { name: "10 côtelettes d'agneau", pic: "côtelette-agneau" },
        { name: "175g chapelure", pic: "chapelure" },
        { name: "10g parmesan", pic: "parmesan" },
        { name: "2 oeufs", pic: "oeuf" },
        { name: "huile", pic: "huile" },
      ],
      serving: 4,
      time: "20 min",
      pic: "crispy-lamb-chops.jpg",
      link: "https://www.nigella.com/recipes/crispy-lamb-chops",
    },
    {
      id: 8,
      name: "Steak tartare au couteau",
      ingredients: [
        { name: "300g boeuf", pic: "boeuf" },
        { name: "1/2 oignon", pic: "oignon" },
        { name: "sauce Worcestershire", pic: "Worcestershire" },
        { name: "moutarde", pic: "moutarde" },
        { name: "tabasco", pic: "tabasco" },
        { name: "1 oeuf", pic: "oeuf" },
        { name: "ketchup", pic: "ketchup" },
      ],
      serving: 2,
      time: "15 min",
      pic: "steak-tartare.jpg",
      link: "https://www.750g.com/steak-tartare-r100092.htm",
    },
    {
      id: 9,
      name: "Risotto pesto chèvre",
      ingredients: [
        { name: "200g riz risotto", pic: "riz" },
        { name: "bouillon poulet", pic: "bouillon-poulet" },
        { name: "pesto", pic: "pesto" },
        { name: "100g bûche chèvre", pic: "bûche-chèvre" },
        { name: "huile", pic: "huile" },
      ],
      serving: 2,
      time: "30 min",
      pic: "risotto-pesto-chèvre.jpg",
      link: "https://www.bbcgoodfood.com/recipes/pesto-goats-cheese-risotto",
    },
    {
      id: 10,
      name: "Risotto alla parmigiana",
      ingredients: [
        { name: "200g riz risotto", pic: "riz" },
        { name: "1 oignon", pic: "oignon" },
        { name: "40g parmesan", pic: "parmesan" },
        { name: "beurre", pic: "beurre" },
        { name: "huile", pic: "huile" },
        { name: "bouillon poulet", pic: "bouillon-poulet" },
      ],
      serving: 2,
      time: "30 min",
      pic: "risotto-parmigiana.jpg",
      link: "https://www.marmiton.org/recettes/recette_risotto-au-parmesan-tres-rapide_341933.aspx",
    },
    {
      id: 11,
      name: "Viande random",
      flag: "random",
      pic: "viande-random.jpg",
    },
    {
      id: 12,
      name: "Potée liégeoise",
      ingredients: [
        { name: "400g lardons", pic: "lardons" },
        { name: "2 oignons", pic: "oignon" },
        { name: "40g beurre", pic: "beurre" },
        { name: "800g haricots verts", pic: "haricot-vert" },
        { name: "800g pommes de terre", pic: "patate" },
      ],
      serving: 4,
      time: "1h15",
      pic: "salade-liégeoise.jpg",
      link: "https://www.marmiton.org/recettes/recette_salade-liegeoise-de-marielle_25279.aspx",
    },
    // {
    //   id: 13,
    //   name: "Oh bah mince on commande !",
    //   flag: "random",
    //   pic: "takeaway.jpg",
    // },

    // Cheesy lemon pasta
    // ramen
    // al fume
    // petit déj anglais
    // lasagne maison
    //burrito
    //ceviche
  ],
};
